version: '3.8'

services:
  linebot:
    build: .
    container_name: linebot-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # LINE Bot 配置
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      
      # Zeabur n8n 配置
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      
      # Bot 配置
      - BOT_NAME=${BOT_NAME:-assistant}
      
      # Dialogflow 配置（可選）
      - DIALOGFLOW_PROJECT_ID=${DIALOGFLOW_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      
      # 數據持久化配置
      - DATA_DIR=/app/data
      - BACKUP_INTERVAL_HOURS=${BACKUP_INTERVAL_HOURS:-24}
      
      # 日誌配置
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # 網路配置
      - WEBHOOK_TIMEOUT=${WEBHOOK_TIMEOUT:-30}
      - MAX_RETRY_ATTEMPTS=${MAX_RETRY_ATTEMPTS:-3}
      
    volumes:
      # 數據持久化 Volume
      - ./data:/app/data
      
      # 如果使用 Google Service Account，需要mount credential文件
      # - ./credentials:/app/credentials:ro
      
    # 甲骨文雲 1C1V 優化配置
    deploy:
      resources:
        limits:
          memory: 450M        # 保守記憶體限制，給系統留空間
          cpus: '0.8'         # 保留 CPU 給系統
        reservations:
          memory: 200M        # 最低保證記憶體
          cpus: '0.2'         # 最低保證 CPU
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 60s           # 延長間隔減少資源消耗
      timeout: 15s
      retries: 3
      start_period: 45s       # 給容器更多啟動時間
    
    # 甲骨文雲日誌優化
    logging:
      driver: "json-file"
      options:
        max-size: "5m"        # 減小日誌文件大小
        max-file: "2"         # 減少日誌文件數量

# Named volumes for data persistence
volumes:
  linebot_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data

# Networks
networks:
  default:
    name: linebot-network
